### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [shanthiacharya/jamming#1]
### Criteria 1: App Creation, Folder Structure, and File Paths
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Project is a CRA app and all components are properly located inside folders.
 
### Criteria 2: Correct Implementation of User Flows
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Correct implementation of user flows (e.g. searching, token generation, save playlist, etc.)
 
### Criteria 3: Proper JavaScript and JSX Syntax and Formatting
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Nice job with proper JS and JSX syntax and formatting!
 
### Criteria 4: Implementation Adheres to DRY Principles
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code is clean, concise, and not repetitive.
 
### Overall Score: 16/16
 
Excellent job on this project! It looks like you have a great understanding of the overall structure of the app as well as each individual components. You also seem to have a solid grasp on making the API requests, including chaining the `.then()` methods.
 
The code is overall very well-written and concise! Great use of JS array methods as well as ternary operator - although another place you could use the latter is [here](https://github.com/shanthiacharya/jamming/blob/55a8d1d1fc05bd0ccfdc90b88663f23746dff042/src/components/Track/Track.js#L28-L31).
 
And an additional detail you can add to the app is to have the playlist reset after the user saves a playlist (ie. _clear the tracks in playlist container and reset name to the default value_). This can help improve user experience, as currently, it is not immediately apparent whether saving of playlist is successful after the user clicks `Save to Spotify`.
 
But again, well done on this project! As a further challenge, feel free to continue to explore the [Spotify API](https://developer.spotify.com/documentation/web-api/reference/) and see if you're able to add more features to this app. Have fun! :)

**Comment by shanthiacharya** [comment]
@cyouh95 Thanks for the great feedback. I fixed the 2 issues and checked in.
